### ISSUE TITLE
Looking forward to the source code

### ISSUE THREAD

**Issue by juyongjiang** [tsukushiAI/self-organized-agent#1]
Hi there,

I am very interested in your work. Could you kindly share your source code? 
Thank you. : )

**Comment by hgcdanniel** [comment]
Hi there,

I am also  very interested in your work. Could you kindly share your source code?
Thank you. : )

**Comment by thumarrushik** [comment]
Hi there,

I am also very interested in your work. Could you kindly share your source code?
Thank you. : )

**Comment by Szzer1** [comment]
Hi there,

I am also very interested in your work. Could you kindly share your source code?
Thank you. : )

**Comment by DCJsenior** [comment]
Hi there,

I am very interested in your work. Could you kindly share your source code?
Thank you. : )
